import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';
import '../models/country.dart';

part 'api_service.g.dart'; // This part file will be generated by Retrofit

@RestApi(baseUrl: "https://restcountries.com/v3.1/") // Define the base URL for the REST API
abstract class ApiService {
    // Factory constructor to create an instance of ApiService with optional baseUrl
  factory ApiService(Dio dio, {String baseUrl}) = _ApiService;


  // Define the endpoint for fetching a list of countries from the API
  @GET("region/europe?fields=name,capital,flags,region,languages,population")
  Future<List<Country>> fetchCountries();
}
